### ISSUE TITLE
使用事件发布机制以支持扩展自定义数据

### ISSUE THREAD

**Issue by hotoo** [saijs/sai.js#18]
包括 #17 中提到的页面 ID，还有其他可能需要用到的非通用数据，比如需要跟服务端 Session 关联的 cookie/SessionID 信息，这些都可以有最佳实践，但每个场景的需要都不相同，不应该内置。

因此考虑提供事件发布机制，用户在需要时，可以扩展自定义数据。

``` js
seajs.use("monitor", function(monitor){
  monitor.on("jserror", function(data){
    data.pageid = "{PAGE_ID}";
    data.cookieid = "{COOKIE_ID}";
  });

  monitor.boot();
});
```

**Comment by lifesinger** [comment]
boot 是启动的意思？

2013/7/22 闲耘(tm) notifications@github.com

> 包括 #17 https://github.com/totorojs/monitor.js/issues/17 中提到的页面
> ID，还有其他可能需要用到的非通用数据，比如需要跟服务端 Session 关联的 cookie/SessionID
> 信息，这些都可以有最佳实践，但每个场景的需要都不相同，不应该内置。
> 
> 因此考虑提供事件发布机制，用户在需要时，可以扩展自定义数据。
> 
> seajs.use("monitor", function(monitor){
>   monitor.on("jserror", function(data){
>     data.pageid = "{PAGE_ID}";
>     data.cookieid = "{COOKIE_ID}";
>   });
> 
>   monitor.boot();});
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/monitor.js/issues/18
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by hotoo** [comment]
启动。前端监控是采样的，默认不启动监控，采样命中时启动监控。
